const hayakuti =[
{read:'あぶりカルビ',write:'aburikarubi'},
{read:'お綾や、八百屋におあやまり',write:'oayaya,yaoyanioayamari'},
{read:'この杭の釘は引き抜きにくい',write:'konokuinokugihahikinukinikui'},
{read:'この寿司は少し酢がききすぎた',write:'konosusihasukosisugakikisugita'},
{read:'この釘はひきぬきにくい釘だ',write:'kokukugihahikinukinikuikugida'},
{read:'ジャズシャンソン歌手',write:'jazusyansonkasyu'},
{read:'マグマ大使のママ マママグマ大使',write:'magumataisinomamamamamagumataisi'},
{read:'むさしのむさしが原の武蔵坊弁慶',write:'musasinomusasigaharanomusasiboubenkei'},
{read:'貨客船の旅客',write:'kakyakusennnoryokyaku'},
{read:'駒込のわがまま者 中野の怠け者',write:'kakekominowagamamamononakanononamakemono'},
{read:'高架橋橋脚',write:'koukakyoukyoukyaku'},
{read:'四百四病で死なぬ信心の力',write:'sihyakusibyoudesinanusinjinnnotikara'},
{read:'除雪車除雪作業中',write:'josetusyajosetusagyoutyuu'},
{read:'生麦生米生卵',write:'namamuginamagomenamatamago'},
{read:'青巻紙赤巻紙黄巻紙',write:'aomakigamiakamakigamikimakigami'},
{read:'赤パジャマ黄パジャマ茶パジャマ',write:'akapajamakipajamatyapajama'},
{read:'第一著者 第二著者 第三著者',write:'daiitityosyadainityosyadaisantyosya'},
{read:'地味な爺やの自慢の地酒',write:'jiminajiiyanojimannnojizake'},
{read:'庭には鶏が二羽いました',write:'niwanihaniwatoriganiwaimasita'},
{read:'東京特許許可局許可局長',write:'toukyoutokkyokyokakyoku'},
{read:'不幸な夫婦は古い服',write:'fukounafuufuhafuruifuku'},
{read:'魔術師魔術修業中',write:'majutusimajutusyugyoutyuu'},
{read:'隣の客はよく柿食う客だ',write:'tonarinokyakuhayokukakikuukyakuda'},
{read:'老若男女',write:'rounyakunannnyo'},
]
